anorak : jacket
blazer : jacket
blouse : blouse
bomber : jacket
button-down : shirt
caftan : blouse
capris : pants
cardigan : sweater
chinos : pants
coat : coat
coverup : none
culottes : pants
cutoffs : none
dress : none
flannel : shirt
gauchos : pants
halter : shirt
henley : sweater
hoodie : sweater
jacket : jacket
jeans : pants
jeggings : pants
jersey : shirt
jodhpurs : pants
joggers : pants
jumpsuit : none
kaftan : none
kimono : none
leggings : pants
onesie : none
parka : coat
peacoat : coat
poncho : coat
robe : coat
romper : none
sarong : none
shorts : none
skirt : none
sweater : sweater
sweatpants : pants
sweatshorts : none
tank : shirt
tee : shirt
top : none
trunks : pants
turtleneck : sweater