jello: 1
tropicana: 2
blue bottle: 3
milano: 4
pringles: 5
melatonin: 6
espresso: 7
pepper: 8
agar: 9
ramen: 9
glade: 9
face wash: 10
gushers: 11
dried mangos: 12
apple: 13
orange: 14
shampoo: 15
plant food: 16
soup: 17