jello: 1
pepper: 2
agar: 3
melatonin: 4
espresso: 5
face wash: 6
apple: 7
orange: 7
glade: 8
soup: 8
ramen: 9
milano: 9
shampoo: 9
tropicana: 10
pringles: 10
blue bottle: 11
plant food: 11
dried mangos: 12
gushers: 12