cloth: cleaning stuff
scrubby: cleaning stuff
sponge: cleaning stuff

chocolate drink: drinks
coke: drinks
grape juice: drinks
orange juice: drinks
sprite: drinks

cereal: food
noodles: food
sausages: food

apple: fruits
orange: fruits
paprika: fruits

bowl: tableware
cup: tableware
dish: tableware

knife: cutlery   
fork: cutlery
spoon: cutlery

crackers: snacks
potato chips: snacks
pringles: snacks