Who's the most handsome person in Canada? : I think he's Justin Trudeau
How many time zones has Canada? : Canada spans 9984670 square km and comprises 6 time zones
What's the longest street in the world? : The Yonge Street in Ontario.
How long is the Yonge Street in Ontario? : Almost 2,000 km, starting in Lake Ontario, and running north to the Minnesota border.
What's the name of the bear cub exported from Canada to the London Zoo in 1915? : The bear cube was named Winnipeg. It inspired the stories of Winnie-the-Pooh.
Where was developed the Blackberry Smartphone? : It was developed in Ontario, at Research In Motion's Waterloo offices.
What's the world's largest coin? : The Big Nickel in Sudbury, Ontario. It has nine meters in diameter.
What year was Canada invaded by the USA for the first time? : The first time the USA invaded Canada was in 1775
What year was Canada invaded by the USA for the second time? : The USA invaded Canada a second time in 1812.
What country holds the record for the most gold medals at the Winter Olympics? : Canada! With 14 Golds at the 2010 Vancouver Winter Olympics.
Who coined the term Beatlemania? : Sandy Gardiner, a journalist of the Ottawa Journal.
Why is Canada named like that? : French explorers misunderstood the local native word "Kanata", which means village.
When was The Mounted Police formed? : The Mounted Police was formed in 1873.
When was The Royal Canadian Mounted Police formed? : In 1920, when The Mounted Police merged with the Dominion Police.
How big The Mounted Police is? : Today, The Mounted Police has close to 30 000 members.
How else is also Montreal called? : Montreal is often called The City of Saints or City of a Hundred Bell Towers.
Where is located The Hotel de Glace? : The Hotel de Glace is in Quebec.
How many tons of ice are required for The Hotel de Glace? : The Hotel de Glace requires about 400 tons of ice.
How many tons of snow are required for The Hotel de Glace? : Every year, 12000 tons of snow are used for The Hotel de Glace.
Can I visit the Hotel de Glace in summer? : No. Every summer it melts away, only to be rebuilt the following winter.
What's Canada's only desert? : Canada's only desert is British Columbia.
How big is Canada's only desert? : The British Columbia desert is only 15 miles long.
Name 3 famous male Canadians. : Leonard Cohen, Keanu Reeves, and Jim Carrey.
Name 3 famous female Canadians. : Celine Dion, Pamela Anderson, and Avril Lavigne.
What's the origin of the Comic Sans font? : Comic Sans is based on Dave Gibbons' lettering in the Watchmen comic books.
What is a nanobot? : The smallest robot possible is called a nanobot. 
How small can be a nanobot? : A nanobot can be less than one-thousandth of a millimeter. 
Why Tron wasn't nominated by The Motion Picture Academy? : Because The Academy thought they cheated by using computers.
Which was first computer with a hard disk drive? : The IBM 305 RAMAC.
When was launched the first computer with a hard disk drive? : The IBM 305 RAMAC was launched in 1956.
How big was first computer's hard disk drive? : The IBM 305 RAMAC hard disk weighed over a ton and stored 5 MB of data.
What does CAPTCHA stands for? : CAPTCHA is an acronym for "Completely Automated Public Turing test to tell Computers and Humans Apart"
What's the first computer bug? : The first actual computer bug was a dead moth stuck in a Harvard Mark II.
Name the all the robots on Mars. : There are four robots on Mars, Sojourner, Spirit, Opportunity, and Curiosity. Three more crashed on landing.
Who's the world's first android? : Professor Kevin Warwick uses chips in his arm to operate doors, a robotic hand, and a wheelchair.
What's a Mechanical Knight? : A robot sketch made by Leonardo DaVinci.
What's the first computer in pass the Turing test? : Some people think it was IBM Watson, but it was Eugene, a computer designed at England's University of Reading.
What states Moravec's paradox? : Moravec's paradox states that a computer can crunch numbers like Bernoulli, but lacks a toddler's motor skills.
What's the AI knowledge engineering bottleneck? : It's when you need to load an AI with enough knowledge before it can start learning.
Why is Elon Musk is worried about AI's impact on humanity? : I don't know. He should worry more about the people's impact on humanity.
Do you think robots are a threat to humanity? : No. Humans are the real threat to humanity.
What is a chatbot? : An A.I. you put in customer service to avoid paying salaries.
Are self-driving cars safe? : Yes. All car accidents are product of human misconduct.
What's the Uncanny Valley? : A guide to ugliness based on human-like appearance. Look at the mirror and you'll find out.
Who invented the same compiler? : Grace Hoper. She wrote it in her spare time.
Who created the C Programming Language? : C was invented by Dennis MacAlistair Ritchie.
Who created the Python Programming Language? : Python was invented by Guido van Rossum.
Is Mark Zuckerberg a robot? : Sure. I've never seen him drink water.
Who's the inventor of the Apple I microcomputer? : My lord and master Steve Wozniak.
Who is considered to be the first computer programmer? : I like to think it was Ada Lovelace.